import "./globals.css";

// Custom CSS for client
import "../styles/index.scss";

import Header from "@/components/includes/header";

import localFont from "next/font/local";

// Define the custom font
const spaceMono = localFont({
  src: [
    {
      path: "../../public/fonts/SpaceMono-Regular.ttf", // Correct path
      weight: "400"
    },
    {
      path: "../../public/fonts/SpaceMono-Bold.ttf",
      weight: "900"
    }
  ],
  variable: '--font-space-mono'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceMono.className}>
      <body className="font-spaceMono">
        <Header />
        {children}
      </body>
    </html>
  );
}